import "server-only";

import path from "node:path";

import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";

import type { MonthlyHoursReport } from "@/lib/hours-report";

type ReportLocale = "en" | "ar";

const logoPath = path.join(process.cwd(), "public", "bytech-logo.png");
const brandFont = path.join(process.cwd(), "public", "fonts", "baloo-bhaijaan-2-semibold.ttf");
const arabicFont = path.join(process.cwd(), "public", "fonts", "dejavu-sans.ttf");

const palette = {
  primary: "#435266",
  orange: "#EF7D00",
  blue: "#4997C2",
  ink: "#171717",
  gray: "#647184",
  line: "#D8DEE6",
  soft: "#F4F7FA",
  white: "#FFFFFF",
  success: "#28754D",
  danger: "#A13F24",
};

const copy = {
  en: {
    title: "EMPLOYEE HOURS REPORT",
    period: "Report month",
    scope: "Access scope",
    expected: "Expected",
    approved: "Approved",
    pending: "Pending",
    rejected: "Rejected",
    missing: "Missing to date",
    overtime: "Overtime",
    cost: "Time cost",
    employees: "EMPLOYEE SUMMARY",
    employee: "Employee",
    department: "Department",
    recorded: "Recorded",
    leave: "Leave",
    projects: "PROJECT DISTRIBUTION",
    project: "Project",
    daily: "DAILY DETAIL",
    date: "Date",
    dayType: "Day type",
    workday: "Workday",
    weekend: "Weekend",
    holiday: "Official holiday",
    task: "Task",
    noRows: "No records for this section.",
    generated: "Generated by Bytech Project Management",
    page: "Page",
  },
  ar: {
    title: "تقرير ساعات الموظفين",
    period: "شهر التقرير",
    scope: "نطاق الصلاحية",
    expected: "المطلوب",
    approved: "المعتمد",
    pending: "المعلق",
    rejected: "المرفوض",
    missing: "الناقص حتى اليوم",
    overtime: "الإضافي",
    cost: "تكلفة الوقت",
    employees: "ملخص الموظفين",
    employee: "الموظف",
    department: "القسم",
    recorded: "المسجل",
    leave: "الإجازات",
    projects: "التوزيع على المشاريع",
    project: "المشروع",
    daily: "التفصيل اليومي",
    date: "التاريخ",
    dayType: "نوع اليوم",
    workday: "يوم عمل",
    weekend: "عطلة أسبوعية",
    holiday: "عطلة رسمية",
    task: "التاسك",
    noRows: "لا توجد سجلات في هذا القسم.",
    generated: "تم إنشاؤه بواسطة نظام إدارة مشاريع Bytech",
    page: "صفحة",
  },
} as const;

function hours(minutes: number | null) {
  return minutes == null ? "-" : `${(minutes / 60).toFixed(minutes % 60 === 0 ? 0 : 2)} h`;
}

function numericHours(minutes: number | null) {
  return minutes == null ? null : Number((minutes / 60).toFixed(2));
}

function money(value: number | null, currency: string) {
  return value == null ? "-" : `${currency} ${value.toFixed(2)}`;
}

function formatDate(date: Date) {
  return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" }).format(date);
}

function localizedText(value: string, lang: ReportLocale) {
  if (lang !== "ar" || !/[\u0600-\u06ff]/.test(value)) return value;
  return value.split("\n").map((line) => line.trim().split(/\s+/).reverse().join(" ")).join("\n");
}

function reportMonth(report: MonthlyHoursReport, lang: ReportLocale) {
  return new Intl.DateTimeFormat(lang === "ar" ? "ar-JO" : "en-GB", {
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  }).format(report.range.start);
}

type PdfColumn = { key: string; header: string; width: number; align?: "left" | "right" | "center" };

function pdfTable(
  doc: PDFKit.PDFDocument,
  title: string,
  columns: PdfColumn[],
  rows: Array<Record<string, string>>,
  startY: number,
  lang: ReportLocale,
) {
  let y = startY;
  const headerHeight = 23;
  const rowHeight = 25;
  const drawHeader = () => {
    doc.rect(46, y, 503, headerHeight).fill(palette.primary);
    let x = 46;
    for (const column of columns) {
      doc.fillColor(palette.white).fontSize(7.2).text(localizedText(column.header, lang), x + 4, y + 7, {
        width: column.width - 8,
        align: column.align ?? (lang === "ar" ? "right" : "left"),
        lineBreak: false,
        ellipsis: true,
      });
      x += column.width;
    }
    y += headerHeight;
  };
  const section = localizedText(title, lang);
  doc.fillColor(palette.primary).fontSize(10.5).text(section, 46, y, { width: 503, align: lang === "ar" ? "right" : "left" });
  doc.moveTo(46, y + 17).lineTo(549, y + 17).lineWidth(1).strokeColor(palette.orange).stroke();
  y += 25;
  drawHeader();

  if (!rows.length) rows = [{ [columns[0].key]: copy[lang].noRows }];
  for (let index = 0; index < rows.length; index += 1) {
    if (y + rowHeight > 755) {
      doc.addPage();
      y = 48;
      drawHeader();
    }
    const row = rows[index];
    if (index % 2 === 0) doc.rect(46, y, 503, rowHeight).fill(palette.soft);
    let x = 46;
    for (const column of columns) {
      doc.fillColor(palette.ink).fontSize(7.2).text(localizedText(row[column.key] ?? "-", lang), x + 4, y + 7, {
        width: column.width - 8,
        align: column.align ?? (lang === "ar" ? "right" : "left"),
        lineBreak: false,
        ellipsis: true,
      });
      x += column.width;
    }
    y += rowHeight;
  }
  return y + 15;
}

export async function buildMonthlyHoursPdf(report: MonthlyHoursReport, lang: ReportLocale) {
  const c = copy[lang];
  const doc = new PDFDocument({
    size: "A4",
    margins: { top: 42, right: 46, bottom: 48, left: 46 },
    bufferPages: true,
    info: { Title: `${c.title} - ${report.range.month}`, Author: "Bytech", Creator: "Bytech Project Management" },
  });
  doc.registerFont("Brand", lang === "ar" ? arabicFont : brandFont);
  doc.font("Brand");
  const chunks: Buffer[] = [];
  doc.on("data", (chunk) => chunks.push(chunk));
  const completed = new Promise<Uint8Array>((resolve, reject) => {
    doc.on("end", () => resolve(new Uint8Array(Buffer.concat(chunks))));
    doc.on("error", reject);
  });

  doc.image(logoPath, 46, 38, { width: 88 });
  doc.fillColor(palette.primary).fontSize(17).text(localizedText(c.title, lang), 190, 44, { width: 359, align: lang === "ar" ? "right" : "left" });
  doc.fillColor(palette.gray).fontSize(8).text(localizedText(c.generated, lang), 190, 68, { width: 359, align: lang === "ar" ? "right" : "left" });
  doc.moveTo(46, 92).lineTo(549, 92).lineWidth(2).strokeColor(palette.orange).stroke();

  doc.fillColor(palette.gray).fontSize(8).text(localizedText(c.period, lang), 46, 109);
  doc.fillColor(palette.ink).fontSize(10).text(localizedText(reportMonth(report, lang), lang), 46, 123);
  doc.fillColor(palette.gray).fontSize(8).text(localizedText(c.scope, lang), 250, 109);
  doc.fillColor(palette.ink).fontSize(10).text(report.access.scope.toUpperCase(), 250, 123);

  const metrics = [
    [c.expected, hours(report.totals.expectedMinutes)],
    [c.approved, hours(report.totals.approvedMinutes)],
    [c.pending, hours(report.totals.pendingMinutes)],
    [c.missing, hours(report.totals.missingMinutes)],
    [report.access.canViewCosts ? c.cost : c.overtime, report.access.canViewCosts ? money(report.totals.cost, report.organization.baseCurrency) : hours(report.totals.overtimeMinutes)],
  ];
  const metricWidth = 97;
  metrics.forEach(([label, value], index) => {
    const x = 46 + (index * (metricWidth + 4));
    doc.roundedRect(x, 153, metricWidth, 54, 5).fill(palette.soft);
    doc.fillColor(palette.gray).fontSize(7).text(localizedText(label, lang), x + 7, 163, { width: metricWidth - 14, align: lang === "ar" ? "right" : "left" });
    doc.fillColor(index === 3 && report.totals.missingMinutes ? palette.danger : palette.primary).fontSize(11).text(value, x + 7, 181, { width: metricWidth - 14, align: lang === "ar" ? "right" : "left" });
  });

  let y = pdfTable(doc, c.employees, [
    { key: "employee", header: c.employee, width: 128 },
    { key: "department", header: c.department, width: 90 },
    { key: "expected", header: c.expected, width: 55, align: "right" },
    { key: "approved", header: c.approved, width: 55, align: "right" },
    { key: "pending", header: c.pending, width: 55, align: "right" },
    { key: "missing", header: c.missing, width: 75, align: "right" },
    { key: "cost", header: report.access.canViewCosts ? (lang === "ar" ? "التكلفة" : "Cost") : c.overtime, width: 45, align: "right" },
  ], report.employees.map((employee) => ({
    employee: employee.name,
    department: employee.department?.name ?? "-",
    expected: hours(employee.expectedMinutes),
    approved: hours(employee.approvedMinutes),
    pending: hours(employee.pendingMinutes),
    missing: hours(employee.missingMinutes),
    cost: report.access.canViewCosts ? money(employee.cost, report.organization.baseCurrency) : hours(employee.overtimeMinutes),
  })), 230, lang);

  y = pdfTable(doc, c.projects, [
    { key: "project", header: c.project, width: 218 },
    { key: "approved", header: c.approved, width: 80, align: "right" },
    { key: "pending", header: c.pending, width: 80, align: "right" },
    { key: "rejected", header: c.rejected, width: 70, align: "right" },
    { key: "cost", header: report.access.canViewCosts ? c.cost : c.recorded, width: 55, align: "right" },
  ], report.projects.map((project) => ({
    project: `${project.code} · ${project.name}`,
    approved: hours(project.approvedMinutes),
    pending: hours(project.pendingMinutes),
    rejected: hours(project.rejectedMinutes),
    cost: report.access.canViewCosts ? money(project.cost, report.organization.baseCurrency) : hours(project.approvedMinutes + project.pendingMinutes),
  })), y, lang);

  if (report.employees.length === 1) {
    const employee = report.employees[0];
    pdfTable(doc, `${c.daily} — ${employee.name}`, [
      { key: "date", header: c.date, width: 100 },
      { key: "type", header: c.dayType, width: 103 },
      { key: "expected", header: c.expected, width: 60, align: "right" },
      { key: "approved", header: c.approved, width: 60, align: "right" },
      { key: "pending", header: c.pending, width: 60, align: "right" },
      { key: "missing", header: c.missing, width: 60, align: "right" },
      { key: "overtime", header: c.overtime, width: 60, align: "right" },
    ], employee.days.map((day) => ({
      date: formatDate(day.date),
      type: day.holiday?.name ?? (day.leaves.length ? day.leaves.map((leave) => leave.type).join(" · ") : day.isWorkday ? c.workday : c.weekend),
      expected: hours(day.expectedMinutes),
      approved: hours(day.approvedMinutes),
      pending: hours(day.pendingMinutes),
      missing: hours(day.missingMinutes),
      overtime: hours(day.overtimeMinutes),
    })), y, lang);
  }

  const pageCount = doc.bufferedPageRange().count;
  for (let pageIndex = 0; pageIndex < pageCount; pageIndex += 1) {
    doc.switchToPage(pageIndex);
    doc.moveTo(46, 750).lineTo(549, 750).lineWidth(0.7).strokeColor(palette.line).stroke();
    doc.fillColor(palette.gray).fontSize(7).text(`${c.page} ${pageIndex + 1} / ${pageCount}`, 46, 758, { width: 503, align: "right", lineBreak: false });
  }
  doc.end();
  return completed;
}

function styleWorksheet(sheet: ExcelJS.Worksheet, title: string, subtitle: string) {
  sheet.views = [{ state: "frozen", ySplit: 5, showGridLines: false }];
  sheet.mergeCells("A1:J1");
  sheet.getCell("A1").value = title;
  sheet.getCell("A1").font = { name: "Aptos Display", size: 18, bold: true, color: { argb: "FF435266" } };
  sheet.getCell("A1").alignment = { vertical: "middle" };
  sheet.getRow(1).height = 30;
  sheet.mergeCells("A2:J2");
  sheet.getCell("A2").value = subtitle;
  sheet.getCell("A2").font = { name: "Aptos", size: 10, color: { argb: "FF647184" } };
  sheet.getRow(3).height = 8;
}

function styleTableHeader(row: ExcelJS.Row) {
  row.height = 23;
  row.eachCell((cell) => {
    cell.font = { name: "Aptos", size: 10, bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF435266" } };
    cell.alignment = { vertical: "middle", horizontal: "left" };
    cell.border = { bottom: { style: "thin", color: { argb: "FFEF7D00" } } };
  });
}

function applyRows(sheet: ExcelJS.Worksheet, startRow: number, endRow: number) {
  for (let rowNumber = startRow; rowNumber <= endRow; rowNumber += 1) {
    const row = sheet.getRow(rowNumber);
    row.font = { name: "Aptos", size: 10, color: { argb: "FF171717" } };
    if ((rowNumber - startRow) % 2 === 0) {
      row.eachCell((cell) => { cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF4F7FA" } }; });
    }
  }
}

export async function buildMonthlyHoursWorkbook(report: MonthlyHoursReport, lang: ReportLocale) {
  const c = copy[lang];
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Bytech Project Management";
  workbook.created = new Date();
  workbook.modified = new Date();
  workbook.properties.date1904 = false;

  const summary = workbook.addWorksheet("Summary", { properties: { tabColor: { argb: "FFEF7D00" } } });
  styleWorksheet(summary, c.title, `${report.organization.name} · ${reportMonth(report, lang)} · ${report.access.scope.toUpperCase()}`);
  summary.addRow([]);
  summary.addRow([c.expected, numericHours(report.totals.expectedMinutes), c.approved, numericHours(report.totals.approvedMinutes), c.pending, numericHours(report.totals.pendingMinutes), c.missing, numericHours(report.totals.missingMinutes), report.access.canViewCosts ? c.cost : c.overtime, report.access.canViewCosts ? report.totals.cost : numericHours(report.totals.overtimeMinutes)]);
  summary.getRow(4).eachCell((cell, column) => {
    cell.font = { name: "Aptos", bold: column % 2 === 1, size: column % 2 === 1 ? 9 : 12, color: { argb: column % 2 === 1 ? "FF647184" : "FF435266" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF4F7FA" } };
  });
  summary.addRow([c.employee, c.department, c.expected, c.approved, c.pending, c.rejected, c.missing, c.overtime, c.leave, report.access.canViewCosts ? c.cost : ""]);
  styleTableHeader(summary.getRow(5));
  for (const employee of report.employees) {
    summary.addRow([
      employee.name,
      employee.department?.name ?? "",
      numericHours(employee.expectedMinutes),
      numericHours(employee.approvedMinutes),
      numericHours(employee.pendingMinutes),
      numericHours(employee.rejectedMinutes),
      numericHours(employee.missingMinutes),
      numericHours(employee.overtimeMinutes),
      numericHours(employee.leaveMinutes),
      report.access.canViewCosts ? employee.cost : null,
    ]);
  }
  applyRows(summary, 6, summary.rowCount);
  summary.columns = [
    { width: 28 }, { width: 23 }, { width: 13 }, { width: 13 }, { width: 13 },
    { width: 13 }, { width: 13 }, { width: 13 }, { width: 13 }, { width: 16 },
  ];
  for (let col = 3; col <= 9; col += 1) summary.getColumn(col).numFmt = "0.00\" h\"";
  if (report.access.canViewCosts) summary.getColumn(10).numFmt = `\"${report.organization.baseCurrency}\" #,##0.00;[Red]-\"${report.organization.baseCurrency}\" #,##0.00`;
  summary.autoFilter = { from: { row: 5, column: 1 }, to: { row: summary.rowCount, column: 10 } };

  const daily = workbook.addWorksheet("Daily Detail", { properties: { tabColor: { argb: "FF4997C2" } } });
  styleWorksheet(daily, c.daily, `${reportMonth(report, lang)} · ${report.employees.length} ${c.employees.toLowerCase()}`);
  daily.addRow([]);
  daily.addRow([c.employee, c.date, c.dayType, c.expected, c.approved, c.pending, c.rejected, c.missing, c.overtime, report.access.canViewCosts ? c.cost : ""]);
  styleTableHeader(daily.getRow(5));
  for (const employee of report.employees) {
    for (const day of employee.days) {
      daily.addRow([
        employee.name,
        day.date,
        day.holiday?.name ?? (day.leaves.length ? day.leaves.map((leave) => leave.type).join(" · ") : day.isWorkday ? c.workday : c.weekend),
        numericHours(day.expectedMinutes),
        numericHours(day.approvedMinutes),
        numericHours(day.pendingMinutes),
        numericHours(day.rejectedMinutes),
        numericHours(day.missingMinutes),
        numericHours(day.overtimeMinutes),
        report.access.canViewCosts ? day.cost : null,
      ]);
    }
  }
  applyRows(daily, 6, daily.rowCount);
  daily.columns = [{ width: 28 }, { width: 15 }, { width: 24 }, ...Array(7).fill({ width: 13 })];
  daily.getColumn(2).numFmt = "dd mmm yyyy";
  for (let col = 4; col <= 9; col += 1) daily.getColumn(col).numFmt = "0.00\" h\"";
  if (report.access.canViewCosts) daily.getColumn(10).numFmt = `\"${report.organization.baseCurrency}\" #,##0.00;[Red]-\"${report.organization.baseCurrency}\" #,##0.00`;
  daily.autoFilter = { from: { row: 5, column: 1 }, to: { row: daily.rowCount, column: 10 } };

  const projects = workbook.addWorksheet("Projects");
  styleWorksheet(projects, c.projects, reportMonth(report, lang));
  projects.addRow([]);
  projects.addRow(["Code", c.project, c.approved, c.pending, c.rejected, c.recorded, report.access.canViewCosts ? c.cost : ""]);
  styleTableHeader(projects.getRow(5));
  report.projects.forEach((project) => projects.addRow([project.code, project.name, numericHours(project.approvedMinutes), numericHours(project.pendingMinutes), numericHours(project.rejectedMinutes), numericHours(project.approvedMinutes + project.pendingMinutes), report.access.canViewCosts ? project.cost : null]));
  applyRows(projects, 6, projects.rowCount);
  projects.columns = [{ width: 15 }, { width: 35 }, { width: 14 }, { width: 14 }, { width: 14 }, { width: 14 }, { width: 18 }, { width: 12 }, { width: 12 }, { width: 12 }];
  for (let col = 3; col <= 6; col += 1) projects.getColumn(col).numFmt = "0.00\" h\"";
  if (report.access.canViewCosts) projects.getColumn(7).numFmt = `\"${report.organization.baseCurrency}\" #,##0.00;[Red]-\"${report.organization.baseCurrency}\" #,##0.00`;
  projects.autoFilter = { from: { row: 5, column: 1 }, to: { row: projects.rowCount, column: 7 } };

  const tasks = workbook.addWorksheet("Tasks");
  styleWorksheet(tasks, c.task, reportMonth(report, lang));
  tasks.addRow([]);
  tasks.addRow([c.project, c.task, c.approved, c.pending, c.rejected, c.recorded, report.access.canViewCosts ? c.cost : ""]);
  styleTableHeader(tasks.getRow(5));
  report.tasks.forEach((task) => tasks.addRow([task.projectName, task.title, numericHours(task.approvedMinutes), numericHours(task.pendingMinutes), numericHours(task.rejectedMinutes), numericHours(task.approvedMinutes + task.pendingMinutes), report.access.canViewCosts ? task.cost : null]));
  applyRows(tasks, 6, tasks.rowCount);
  tasks.columns = [{ width: 32 }, { width: 38 }, { width: 14 }, { width: 14 }, { width: 14 }, { width: 14 }, { width: 18 }, { width: 12 }, { width: 12 }, { width: 12 }];
  for (let col = 3; col <= 6; col += 1) tasks.getColumn(col).numFmt = "0.00\" h\"";
  if (report.access.canViewCosts) tasks.getColumn(7).numFmt = `\"${report.organization.baseCurrency}\" #,##0.00;[Red]-\"${report.organization.baseCurrency}\" #,##0.00`;
  tasks.autoFilter = { from: { row: 5, column: 1 }, to: { row: tasks.rowCount, column: 7 } };

  const calendar = workbook.addWorksheet("Calendar");
  styleWorksheet(calendar, "WORK CALENDAR", `${reportMonth(report, lang)} · ${report.organization.timezone}`);
  calendar.addRow([]);
  calendar.addRow(["Record type", c.employee, c.date, "End date", "Leave type", "Hours/day", "Paid", "Name"]);
  styleTableHeader(calendar.getRow(5));
  report.holidays.forEach((holiday) => calendar.addRow([c.holiday, "", holiday.date, "", "", "", holiday.isPaid ? "Yes" : "No", holiday.name]));
  report.leaves.forEach((leave) => calendar.addRow([c.leave, report.employeeOptions.find((employee) => employee.id === leave.userId)?.name ?? "", leave.startDate, leave.endDate, leave.type, numericHours(leave.minutesPerWorkday), "", ""]));
  applyRows(calendar, 6, calendar.rowCount);
  calendar.columns = [{ width: 20 }, { width: 28 }, { width: 15 }, { width: 15 }, { width: 18 }, { width: 14 }, { width: 12 }, { width: 32 }, { width: 12 }, { width: 12 }];
  calendar.getColumn(3).numFmt = "dd mmm yyyy";
  calendar.getColumn(4).numFmt = "dd mmm yyyy";
  calendar.getColumn(6).numFmt = "0.00\" h\"";
  calendar.autoFilter = { from: { row: 5, column: 1 }, to: { row: calendar.rowCount, column: 8 } };

  for (const sheet of workbook.worksheets) {
    sheet.pageSetup = { orientation: "landscape", fitToPage: true, fitToWidth: 1, fitToHeight: 0, paperSize: 9, margins: { left: 0.3, right: 0.3, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2 } };
    sheet.headerFooter.oddFooter = `&LBytech&C${report.range.month}&RPage &P of &N`;
  }

  const buffer = await workbook.xlsx.writeBuffer();
  return new Uint8Array(buffer);
}
