import "server-only";

import path from "node:path";

import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";

import type { getProjectProfitabilityReport } from "@/lib/financials";

export type ProjectProfitabilityReport = NonNullable<
  Awaited<ReturnType<typeof getProjectProfitabilityReport>>
>;

export type ReportLocale = "en" | "ar";

const logoPath = path.join(process.cwd(), "public", "bytech-logo.png");
const brandFont = path.join(process.cwd(), "public", "fonts", "baloo-bhaijaan-2-semibold.ttf");
const arabicFont = path.join(process.cwd(), "public", "fonts", "dejavu-sans.ttf");

const palette = {
  primary: "#435266",
  orange: "#EF7D00",
  blue: "#4997C2",
  ink: "#171717",
  gray: "#647184",
  line: "#D8DEE6",
  soft: "#F4F7FA",
  white: "#FFFFFF",
  success: "#28754D",
  danger: "#A13F24",
};

const copy = {
  en: {
    title: "PROJECT PROFITABILITY REPORT",
    generated: "Generated by Bytech Project Management",
    project: "Project",
    client: "Client",
    manager: "Project manager",
    period: "Report period",
    fullPeriod: "Full project to date",
    contract: "Contract value",
    budget: "Planned budget",
    actual: "Actual cost",
    forecast: "Forecast cost",
    profit: "Forecast profit",
    margin: "Forecast margin",
    costBreakdown: "WHOLE-PROJECT COST BREAKDOWN",
    category: "Category",
    approved: "Approved",
    additional: "Additional forecast",
    total: "Forecast total",
    labor: "Labor",
    expenses: "Direct expenses",
    subscriptions: "Allocated subscriptions",
    selectedActivity: "SELECTED-PERIOD ACTIVITY",
    approvedCost: "Approved cost",
    pendingCost: "Pending cost",
    approvedHours: "Approved hours",
    pendingHours: "Pending hours",
    employees: "EMPLOYEE COST BREAKDOWN",
    employee: "Employee",
    jobTitle: "Job title",
    avgRate: "Avg. hourly cost",
    cost: "Total cost",
    tasks: "TASK PERFORMANCE",
    task: "Task",
    status: "Status",
    estimate: "Estimate",
    tracked: "Tracked",
    variance: "Variance",
    remaining: "Remaining",
    due: "Due",
    date: "Date",
    vendor: "Vendor",
    description: "Description",
    amount: "Amount",
    tax: "Tax",
    allocation: "Allocation",
    periodCost: "Period cost",
    invoice: "Invoice",
    issued: "Issued",
    collected: "Collected",
    outstanding: "Outstanding",
    billing: "BILLING AND COLLECTIONS",
    alerts: "FINANCIAL ALERTS",
    noRows: "No records for this section.",
    page: "Page",
  },
  ar: {
    title: "تقرير ربحية المشروع",
    generated: "تم إنشاؤه بواسطة نظام إدارة مشاريع Bytech",
    project: "المشروع",
    client: "العميل",
    manager: "مدير المشروع",
    period: "فترة التقرير",
    fullPeriod: "كامل مدة المشروع حتى اليوم",
    contract: "قيمة العقد",
    budget: "الميزانية المخططة",
    actual: "التكلفة الفعلية",
    forecast: "التكلفة المتوقعة",
    profit: "الربح المتوقع",
    margin: "هامش الربح المتوقع",
    costBreakdown: "تفصيل تكلفة المشروع",
    category: "البند",
    approved: "معتمد",
    additional: "إضافي متوقع",
    total: "الإجمالي المتوقع",
    labor: "تكلفة الموظفين",
    expenses: "المصاريف المباشرة",
    subscriptions: "الاشتراكات الموزعة",
    selectedActivity: "نشاط الفترة المحددة",
    approvedCost: "تكلفة معتمدة",
    pendingCost: "تكلفة معلقة",
    approvedHours: "ساعات معتمدة",
    pendingHours: "ساعات معلقة",
    employees: "تفصيل تكلفة الموظفين",
    employee: "الموظف",
    jobTitle: "المسمى الوظيفي",
    avgRate: "متوسط تكلفة الساعة",
    cost: "التكلفة الإجمالية",
    tasks: "أداء التاسكات",
    task: "التاسك",
    status: "الحالة",
    estimate: "المقدر",
    tracked: "المسجل",
    variance: "الفرق",
    remaining: "المتبقي",
    due: "التسليم",
    date: "التاريخ",
    vendor: "المورد",
    description: "الوصف",
    amount: "المبلغ",
    tax: "الضريبة",
    allocation: "نسبة التوزيع",
    periodCost: "تكلفة الفترة",
    invoice: "الفاتورة",
    issued: "الإصدار",
    collected: "المحصل",
    outstanding: "الرصيد",
    billing: "الفوترة والتحصيل",
    alerts: "التنبيهات المالية",
    noRows: "لا توجد سجلات في هذا القسم.",
    page: "صفحة",
  },
} as const;

function formatDate(date: Date | null | undefined) {
  if (!date) return "-";
  return new Intl.DateTimeFormat("en-GB", {
    year: "numeric",
    month: "short",
    day: "numeric",
    timeZone: "UTC",
  }).format(date);
}

function formatIsoDate(date: Date | null | undefined) {
  return date ? date.toISOString().slice(0, 10) : "-";
}

function money(value: number, currency: string) {
  return `${currency} ${new Intl.NumberFormat("en-JO", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value)}`;
}

function hours(minutes: number) {
  return `${(minutes / 60).toFixed(1)} h`;
}

function localizedText(value: string, lang: ReportLocale) {
  if (lang !== "ar" || !/[\u0600-\u06ff]/.test(value)) return value;
  return value
    .split("\n")
    .map((line) => line.trim().split(/\s+/).reverse().join(" "))
    .join("\n");
}

function reportPeriod(report: ProjectProfitabilityReport, lang: ReportLocale) {
  if (!report.range.from && !report.range.to) return copy[lang].fullPeriod;
  return `${report.range.from ? formatDate(report.range.from) : "Start"} - ${report.range.to ? formatDate(report.range.to) : "Today"}`;
}

type PdfColumn = {
  key: string;
  header: string;
  width: number;
  align?: "left" | "right" | "center";
};

function createPdf(lang: ReportLocale, report: ProjectProfitabilityReport) {
  const doc = new PDFDocument({
    size: "A4",
    margins: { top: 42, right: 46, bottom: 48, left: 46 },
    bufferPages: true,
    info: {
      Title: `${copy[lang].title} - ${report.summary.project.name}`,
      Author: "Bytech",
      Creator: "Bytech Project Management",
    },
  });
  doc.registerFont("Brand", lang === "ar" ? arabicFont : brandFont);
  doc.font("Brand");
  return doc;
}

function pdfSectionTitle(doc: PDFKit.PDFDocument, title: string, y: number, lang: ReportLocale) {
  doc.fillColor(palette.primary).fontSize(11).text(localizedText(title, lang), 46, y, {
    width: 503,
    align: lang === "ar" ? "right" : "left",
  });
  doc.moveTo(46, y + 18).lineTo(549, y + 18).lineWidth(1).strokeColor(palette.orange).stroke();
  return y + 27;
}

function pdfTable(
  doc: PDFKit.PDFDocument,
  title: string,
  columns: PdfColumn[],
  rows: Array<Record<string, string>>,
  startY: number,
  lang: ReportLocale,
) {
  let y = startY;
  const rowHeight = 25;
  const headerHeight = 23;

  const drawTableHeader = () => {
    doc.rect(46, y, 503, headerHeight).fill(palette.primary);
    let x = 46;
    for (const column of columns) {
      doc.fillColor(palette.white).fontSize(7.5).text(localizedText(column.header, lang), x + 5, y + 7, {
        width: column.width - 10,
        align: column.align ?? (lang === "ar" ? "right" : "left"),
        lineBreak: false,
        ellipsis: true,
      });
      x += column.width;
    }
    y += headerHeight;
  };

  const minimumTableHeight = 27 + headerHeight + rowHeight;
  if (y + minimumTableHeight > 744) {
    doc.addPage();
    y = 46;
  }
  y = pdfSectionTitle(doc, title, y, lang);
  drawTableHeader();

  if (!rows.length) {
    doc.rect(46, y, 503, rowHeight).fillAndStroke(palette.soft, palette.line);
    doc.fillColor(palette.gray).fontSize(8).text(localizedText(copy[lang].noRows, lang), 52, y + 8, {
      width: 491,
      align: lang === "ar" ? "right" : "left",
    });
    return y + rowHeight + 15;
  }

  for (const [index, row] of rows.entries()) {
    if (y + rowHeight > 744) {
      doc.addPage();
      y = 46;
      y = pdfSectionTitle(doc, title, y, lang);
      drawTableHeader();
    }
    doc.rect(46, y, 503, rowHeight)
      .fillAndStroke(index % 2 === 0 ? palette.white : palette.soft, palette.line);
    let x = 46;
    for (const column of columns) {
      doc.fillColor(palette.ink).fontSize(7.4).text(localizedText(row[column.key] ?? "-", lang), x + 5, y + 8, {
        width: column.width - 10,
        align: column.align ?? (lang === "ar" ? "right" : "left"),
        lineBreak: false,
        ellipsis: true,
      });
      x += column.width;
    }
    y += rowHeight;
  }
  return y + 15;
}

function addPdfFooters(doc: PDFKit.PDFDocument, lang: ReportLocale) {
  const pages = doc.bufferedPageRange();
  for (let index = pages.start; index < pages.start + pages.count; index += 1) {
    doc.switchToPage(index);
    doc.moveTo(46, 768).lineTo(549, 768).lineWidth(0.7).strokeColor(palette.line).stroke();
    doc.fillColor(palette.gray).fontSize(8).text(localizedText(copy[lang].generated, lang), 46, 777, {
      width: 360,
      align: lang === "ar" ? "right" : "left",
      lineBreak: false,
    });
    doc.text(`${copy[lang].page} ${index + 1} / ${pages.count}`, 430, 777, { width: 119, align: "right", lineBreak: false });
  }
}

function finishPdf(doc: PDFKit.PDFDocument, lang: ReportLocale) {
  return new Promise<Uint8Array>((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(new Uint8Array(Buffer.concat(chunks))));
    doc.on("error", reject);
    addPdfFooters(doc, lang);
    doc.end();
  });
}

function alertLabel(alert: ProjectProfitabilityReport["alerts"][number], lang: ReportLocale) {
  const labels = {
    en: {
      budget: "Forecast exceeds the planned budget",
      margin: "Forecast margin is below target",
      rates: "Employee hours are missing a cost rate",
      tasks: "Tasks are overdue",
      receivables: "Receivables are overdue",
      planning: "Planned budget is missing",
    },
    ar: {
      budget: "التكلفة المتوقعة تتجاوز الميزانية",
      margin: "هامش الربح المتوقع أقل من المستهدف",
      rates: "ساعات موظفين بلا سعر تكلفة",
      tasks: "يوجد تاسكات متأخرة",
      receivables: "يوجد تحصيلات متأخرة",
      planning: "الميزانية المخططة غير محددة",
    },
  } as const;
  return labels[lang][alert.code];
}

export async function buildProjectProfitabilityPdf(
  report: ProjectProfitabilityReport,
  lang: ReportLocale,
) {
  const t = copy[lang];
  const row = report.summary;
  const currency = row.project.currency;
  const doc = createPdf(lang, report);

  doc.rect(0, 0, doc.page.width, 8).fill(palette.orange);
  doc.image(logoPath, 46, 30, { fit: [175, 54] });
  doc.fillColor(palette.primary).fontSize(lang === "ar" ? 18 : 18).text(localizedText(t.title, lang), 242, 42, {
    width: 307,
    align: "right",
  });
  doc.fillColor(palette.gray).fontSize(8.5).text(`${row.project.code} | ${row.project.status.replaceAll("_", " ")}`, 262, 64, {
    width: 287,
    align: "right",
  });
  doc.moveTo(46, 96).lineTo(549, 96).lineWidth(1).strokeColor(palette.line).stroke();

  const details = [
    [t.project, row.project.name],
    [t.client, row.project.client.name],
    [t.manager, row.project.primaryManager.name],
    [t.period, reportPeriod(report, lang)],
  ];
  details.forEach(([label, value], index) => {
    const column = index % 2;
    const line = Math.floor(index / 2);
    const x = 46 + column * 260;
    const y = 111 + line * 34;
    doc.fillColor(palette.blue).fontSize(7.5).text(localizedText(label, lang), x, y, { width: 235, align: lang === "ar" ? "right" : "left" });
    doc.fillColor(palette.ink).fontSize(9.5).text(localizedText(value, lang), x, y + 12, { width: 235, align: lang === "ar" ? "right" : "left", ellipsis: true, lineBreak: false });
  });

  const metrics = [
    [t.contract, money(row.contractValue, currency)],
    [t.budget, money(row.plannedBudget, currency)],
    [t.actual, money(row.actualCost, currency)],
    [t.forecast, money(row.forecastCost, currency)],
    [t.profit, money(row.forecastProfit, currency)],
    [t.margin, `${row.forecastMargin.toFixed(1)}%`],
  ];
  metrics.forEach(([label, value], index) => {
    const column = index % 3;
    const line = Math.floor(index / 3);
    const x = 46 + column * 171;
    const y = 183 + line * 57;
    doc.roundedRect(x, y, 157, 45, 6).fillAndStroke(palette.soft, palette.line);
    doc.fillColor(palette.blue).fontSize(7.2).text(localizedText(label, lang), x + 10, y + 9, { width: 137, align: lang === "ar" ? "right" : "left" });
    doc.fillColor(label === t.profit && row.forecastProfit < 0 ? palette.danger : palette.ink)
      .fontSize(11).text(value, x + 10, y + 23, { width: 137, align: lang === "ar" ? "right" : "left", lineBreak: false, ellipsis: true });
  });

  let y = 307;
  y = pdfTable(doc, t.costBreakdown, [
    { key: "category", header: t.category, width: 170 },
    { key: "approved", header: t.approved, width: 111, align: "right" },
    { key: "additional", header: t.additional, width: 111, align: "right" },
    { key: "total", header: t.total, width: 111, align: "right" },
  ], [
    { category: t.labor, approved: money(row.approvedLaborCost, currency), additional: money(row.pendingLaborCost + row.remainingLaborCost, currency), total: money(row.forecastLaborCost, currency) },
    { category: t.expenses, approved: money(row.approvedExpenses, currency), additional: money(row.pendingExpenses, currency), total: money(row.approvedExpenses + row.pendingExpenses, currency) },
    { category: t.subscriptions, approved: money(row.actualSubscriptions, currency), additional: money(Math.max(row.forecastSubscriptions - row.actualSubscriptions, 0), currency), total: money(row.forecastSubscriptions, currency) },
  ], y, lang);

  y = pdfTable(doc, t.selectedActivity, [
    { key: "metric", header: t.category, width: 220 },
    { key: "value", header: t.amount, width: 142, align: "right" },
    { key: "hours", header: t.tracked, width: 141, align: "right" },
  ], [
    { metric: t.approvedCost, value: money(report.period.actualCost, currency), hours: hours(report.period.approvedMinutes) },
    { metric: t.pendingCost, value: money(report.period.committedCost, currency), hours: hours(report.period.pendingMinutes) },
    { metric: t.subscriptions, value: money(report.period.subscriptionCost, currency), hours: "-" },
  ], y, lang);

  y = pdfTable(doc, t.employees, [
    { key: "employee", header: t.employee, width: 150 },
    { key: "approved", header: t.approvedHours, width: 83, align: "right" },
    { key: "pending", header: t.pendingHours, width: 83, align: "right" },
    { key: "rate", header: t.avgRate, width: 94, align: "right" },
    { key: "cost", header: t.cost, width: 93, align: "right" },
  ], report.employees.map((employee) => ({
    employee: employee.name,
    approved: hours(employee.approvedMinutes),
    pending: hours(employee.pendingMinutes),
    rate: money(employee.averageHourlyCost, currency),
    cost: money(employee.totalCost, currency),
  })), y, lang);

  y = pdfTable(doc, t.tasks, [
    { key: "task", header: t.task, width: 160 },
    { key: "estimate", header: t.estimate, width: 66, align: "right" },
    { key: "tracked", header: t.tracked, width: 66, align: "right" },
    { key: "remaining", header: t.remaining, width: 66, align: "right" },
    { key: "cost", header: t.cost, width: 80, align: "right" },
    { key: "status", header: t.status, width: 65 },
  ], report.tasks.map((task) => ({
    task: task.title,
    estimate: hours(task.estimatedMinutes),
    tracked: hours(task.trackedMinutes),
    remaining: hours(task.remainingMinutes),
    cost: money(task.totalLaborCost, currency),
    status: task.status.replaceAll("_", " "),
  })), y, lang);

  y = pdfTable(doc, t.expenses, [
    { key: "date", header: t.date, width: 79 },
    { key: "vendor", header: t.vendor, width: 110 },
    { key: "description", header: t.description, width: 160 },
    { key: "status", header: t.status, width: 72 },
    { key: "total", header: t.total, width: 82, align: "right" },
  ], report.expenses.map((expense) => ({
    date: formatDate(expense.expenseDate),
    vendor: expense.vendor ?? expense.category,
    description: expense.description,
    status: expense.status,
    total: money(expense.total, currency),
  })), y, lang);

  y = pdfTable(doc, t.subscriptions, [
    { key: "name", header: t.description, width: 160 },
    { key: "vendor", header: t.vendor, width: 100 },
    { key: "allocation", header: t.allocation, width: 78, align: "right" },
    { key: "period", header: t.periodCost, width: 83, align: "right" },
    { key: "forecast", header: t.forecast, width: 82, align: "right" },
  ], report.subscriptions.map((allocation) => ({
    name: allocation.subscription.name,
    vendor: allocation.subscription.vendor,
    allocation: `${allocation.allocationPercent.toFixed(1)}%`,
    period: money(allocation.periodCost, currency),
    forecast: money(allocation.forecastCost, currency),
  })), y, lang);

  y = pdfTable(doc, t.billing, [
    { key: "invoice", header: t.invoice, width: 105 },
    { key: "issued", header: t.issued, width: 86 },
    { key: "due", header: t.due, width: 86 },
    { key: "total", header: t.total, width: 78, align: "right" },
    { key: "collected", header: t.collected, width: 74, align: "right" },
    { key: "outstanding", header: t.outstanding, width: 74, align: "right" },
  ], report.invoicing.invoiceRows.map((invoice) => ({
    invoice: invoice.number,
    issued: formatDate(invoice.issueDate),
    due: formatDate(invoice.dueDate),
    total: money(invoice.total, currency),
    collected: money(invoice.collected, currency),
    outstanding: money(invoice.outstanding, currency),
  })), y, lang);

  if (report.alerts.length) {
    pdfTable(doc, t.alerts, [
      { key: "severity", header: t.status, width: 90 },
      { key: "alert", header: t.description, width: 413 },
    ], report.alerts.map((alert) => ({
      severity: alert.severity.toUpperCase(),
      alert: alertLabel(alert, lang),
    })), y, lang);
  }

  return finishPdf(doc, lang);
}

const excelHeaderFill: ExcelJS.Fill = {
  type: "pattern",
  pattern: "solid",
  fgColor: { argb: "FF435266" },
};

const excelSectionFill: ExcelJS.Fill = {
  type: "pattern",
  pattern: "solid",
  fgColor: { argb: "FFEAF2F7" },
};

function argb(hex: string) {
  return `FF${hex.replace("#", "").toUpperCase()}`;
}

function currencyFormat(currency: string) {
  const safeCurrency = currency.replace(/[^A-Z]/gi, "").slice(0, 6) || "CUR";
  return `"${safeCurrency}" #,##0.00;[Red]("${safeCurrency}" #,##0.00);-`;
}

function styleHeaderRow(row: ExcelJS.Row) {
  row.height = 24;
  row.eachCell((cell) => {
    cell.fill = excelHeaderFill;
    cell.font = { bold: true, color: { argb: "FFFFFFFF" }, size: 10 };
    cell.alignment = { vertical: "middle", horizontal: "left" };
    cell.border = { bottom: { style: "medium", color: { argb: "FFEF7D00" } } };
  });
}

function prepareDataSheet(
  workbook: ExcelJS.Workbook,
  name: string,
  columns: Array<{ header: string; key: string; width: number }>,
  lang: ReportLocale,
) {
  const sheet = workbook.addWorksheet(name, {
    views: [{ state: "frozen", ySplit: 1, showGridLines: false, rightToLeft: lang === "ar" }],
  });
  sheet.columns = columns;
  styleHeaderRow(sheet.getRow(1));
  sheet.autoFilter = { from: "A1", to: `${sheet.getColumn(columns.length).letter}1` };
  sheet.pageSetup = { orientation: "landscape", fitToPage: true, fitToWidth: 1, fitToHeight: 0 };
  return sheet;
}

function styleDataRows(sheet: ExcelJS.Worksheet, headerRows = 1) {
  sheet.eachRow((row, rowNumber) => {
    if (rowNumber <= headerRows) return;
    row.height = 21;
    row.eachCell((cell) => {
      cell.font = { name: "Arial", size: 9.5, color: { argb: "FF171717" } };
      cell.alignment = { vertical: "middle", horizontal: "left" };
      cell.border = { bottom: { style: "hair", color: { argb: "FFD8DEE6" } } };
      if (rowNumber % 2 === 0) cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF7F9FB" } };
    });
  });
}

function styleMoneyColumn(sheet: ExcelJS.Worksheet, keys: string[], format: string) {
  for (const key of keys) {
    const column = sheet.getColumn(key);
    column.numFmt = format;
    column.alignment = { horizontal: "right" };
  }
}

function addEmptySheetMessage(sheet: ExcelJS.Worksheet, lastColumn: string, message: string) {
  sheet.addRow([message]);
  sheet.mergeCells(`A2:${lastColumn}2`);
  const cell = sheet.getCell("A2");
  cell.font = { italic: true, color: { argb: argb(palette.gray) } };
  cell.alignment = { vertical: "middle", horizontal: "left" };
}

export async function buildProjectProfitabilityWorkbook(
  report: ProjectProfitabilityReport,
  lang: ReportLocale,
) {
  const t = copy[lang];
  const row = report.summary;
  const currency = row.project.currency;
  const moneyFormat = currencyFormat(currency);
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Bytech Project Management";
  workbook.lastModifiedBy = "Bytech Project Management";
  workbook.created = new Date();
  workbook.modified = new Date();
  workbook.calcProperties.fullCalcOnLoad = true;

  const summary = workbook.addWorksheet(lang === "ar" ? "الملخص" : "Summary", {
    views: [{ showGridLines: false, rightToLeft: lang === "ar" }],
  });
  summary.columns = [
    { width: 25 }, { width: 20 }, { width: 25 }, { width: 20 }, { width: 25 }, { width: 20 },
  ];
  const logoId = workbook.addImage({ filename: logoPath, extension: "png" });
  summary.addImage(logoId, { tl: { col: 0, row: 0 }, ext: { width: 180, height: 50 } });
  summary.mergeCells("C1:F2");
  const titleCell = summary.getCell("C1");
  titleCell.value = t.title;
  titleCell.font = { name: "Arial", size: 20, bold: true, color: { argb: argb(palette.primary) } };
  titleCell.alignment = { vertical: "middle", horizontal: lang === "ar" ? "right" : "left" };
  summary.getRow(1).height = 28;
  summary.getRow(2).height = 28;

  summary.mergeCells("A4:F4");
  summary.getCell("A4").value = `${row.project.name} | ${row.project.code} | ${row.project.status.replaceAll("_", " ")}`;
  summary.getCell("A4").fill = excelHeaderFill;
  summary.getCell("A4").font = { bold: true, color: { argb: "FFFFFFFF" }, size: 12 };
  summary.getCell("A4").alignment = { vertical: "middle", horizontal: lang === "ar" ? "right" : "left" };
  summary.getRow(4).height = 26;

  const details = [
    [t.client, row.project.client.name],
    [t.manager, row.project.primaryManager.name],
    [t.period, reportPeriod(report, lang)],
  ];
  details.forEach(([label, value], index) => {
    const labelColumn = index * 2 + 1;
    summary.getCell(5, labelColumn).value = label;
    summary.getCell(5, labelColumn + 1).value = value;
    summary.getCell(5, labelColumn).font = { bold: true, color: { argb: argb(palette.blue) } };
  });

  const kpis = [
    { label: t.contract, cell: "B7", value: row.contractValue },
    { label: t.budget, cell: "D7", value: row.plannedBudget },
    { label: t.actual, cell: "F7", value: row.actualCost },
    { label: t.forecast, cell: "B9", value: row.forecastCost },
  ];
  for (const [index, kpi] of kpis.entries()) {
    const labelCell = summary.getCell(index < 3 ? 6 : 8, index < 3 ? index * 2 + 1 : 1);
    labelCell.value = kpi.label;
    labelCell.fill = excelSectionFill;
    labelCell.font = { bold: true, color: { argb: argb(palette.primary) } };
    const valueCell = summary.getCell(kpi.cell);
    valueCell.value = kpi.value;
    valueCell.numFmt = moneyFormat;
    valueCell.font = { bold: true, size: 13, color: { argb: argb(palette.ink) } };
  }
  summary.getCell("C8").value = t.profit;
  summary.getCell("C8").fill = excelSectionFill;
  summary.getCell("C8").font = { bold: true, color: { argb: argb(palette.primary) } };
  summary.getCell("D9").value = { formula: "B7-B9", result: row.forecastProfit };
  summary.getCell("D9").numFmt = moneyFormat;
  summary.getCell("D9").font = { bold: true, size: 13, color: { argb: argb(row.forecastProfit >= 0 ? palette.success : palette.danger) } };
  summary.getCell("E8").value = t.margin;
  summary.getCell("E8").fill = excelSectionFill;
  summary.getCell("E8").font = { bold: true, color: { argb: argb(palette.primary) } };
  summary.getCell("F9").value = { formula: "IF(B7=0,0,D9/B7)", result: row.forecastMargin / 100 };
  summary.getCell("F9").numFmt = "0.0%";
  summary.getCell("F9").font = { bold: true, size: 13, color: { argb: argb(row.forecastMargin >= 0 ? palette.success : palette.danger) } };

  summary.mergeCells("A12:F12");
  summary.getCell("A12").value = t.costBreakdown;
  summary.getCell("A12").fill = excelHeaderFill;
  summary.getCell("A12").font = { bold: true, color: { argb: "FFFFFFFF" } };
  const costRows = [
    [t.category, t.approved, t.additional, t.total],
    [t.labor, row.approvedLaborCost, row.pendingLaborCost + row.remainingLaborCost, row.forecastLaborCost],
    [t.expenses, row.approvedExpenses, row.pendingExpenses, row.approvedExpenses + row.pendingExpenses],
    [t.subscriptions, row.actualSubscriptions, Math.max(row.forecastSubscriptions - row.actualSubscriptions, 0), row.forecastSubscriptions],
    ["Total", { formula: "SUM(B14:B16)", result: row.actualCost }, { formula: "SUM(C14:C16)", result: Math.max(row.forecastCost - row.actualCost, 0) }, { formula: "SUM(D14:D16)", result: row.forecastCost }],
  ];
  costRows.forEach((values, index) => {
    const excelRow = summary.getRow(13 + index);
    excelRow.values = values;
    if (index === 0) styleHeaderRow(excelRow);
    else {
      excelRow.height = 22;
      for (let column = 2; column <= 4; column += 1) excelRow.getCell(column).numFmt = moneyFormat;
      if (index === costRows.length - 1) excelRow.font = { bold: true };
    }
  });

  summary.mergeCells("A19:F19");
  summary.getCell("A19").value = t.selectedActivity;
  summary.getCell("A19").fill = excelHeaderFill;
  summary.getCell("A19").font = { bold: true, color: { argb: "FFFFFFFF" } };
  const periodRows = [
    [t.approvedCost, report.period.actualCost, t.approvedHours, report.period.approvedMinutes / 60],
    [t.pendingCost, report.period.committedCost, t.pendingHours, report.period.pendingMinutes / 60],
    [t.subscriptions, report.period.subscriptionCost, t.expenses, report.period.approvedExpenseCost + report.period.pendingExpenseCost],
  ];
  periodRows.forEach((values, index) => {
    const excelRow = summary.getRow(20 + index);
    excelRow.values = values;
    excelRow.getCell(1).font = { bold: true, color: { argb: argb(palette.blue) } };
    excelRow.getCell(2).numFmt = moneyFormat;
    excelRow.getCell(3).font = { bold: true, color: { argb: argb(palette.blue) } };
    excelRow.getCell(4).numFmt = index < 2 ? "0.0" : moneyFormat;
  });

  summary.mergeCells("A25:F25");
  summary.getCell("A25").value = t.alerts;
  summary.getCell("A25").fill = excelHeaderFill;
  summary.getCell("A25").font = { bold: true, color: { argb: "FFFFFFFF" } };
  if (report.alerts.length) {
    report.alerts.forEach((alert, index) => {
      summary.mergeCells(26 + index, 2, 26 + index, 6);
      summary.getCell(26 + index, 1).value = alert.severity.toUpperCase();
      summary.getCell(26 + index, 1).font = { bold: true, color: { argb: argb(alert.severity === "critical" ? palette.danger : palette.orange) } };
      summary.getCell(26 + index, 2).value = alertLabel(alert, lang);
    });
  } else {
    summary.mergeCells("A26:F26");
    summary.getCell("A26").value = lang === "ar" ? "لا توجد تنبيهات مالية أو تشغيلية حالية." : "No current financial or delivery alerts.";
    summary.getCell("A26").font = { italic: true, color: { argb: argb(palette.success) } };
  }
  summary.pageSetup = { orientation: "landscape", fitToPage: true, fitToWidth: 1, fitToHeight: 1 };
  summary.pageSetup.printArea = `A1:F${Math.max(27, 26 + report.alerts.length)}`;

  const employees = prepareDataSheet(workbook, lang === "ar" ? "الموظفون" : "Employees", [
    { header: t.employee, key: "employee", width: 26 },
    { header: t.jobTitle, key: "jobTitle", width: 22 },
    { header: t.approvedHours, key: "approvedHours", width: 17 },
    { header: t.approvedCost, key: "approvedCost", width: 18 },
    { header: t.pendingHours, key: "pendingHours", width: 17 },
    { header: t.pendingCost, key: "pendingCost", width: 18 },
    { header: "Unpriced hours", key: "unpricedHours", width: 17 },
    { header: t.avgRate, key: "averageRate", width: 20 },
    { header: t.cost, key: "totalCost", width: 18 },
  ], lang);
  report.employees.forEach((employee, index) => employees.addRow({
    employee: employee.name,
    jobTitle: employee.jobTitle ?? "-",
    approvedHours: employee.approvedMinutes / 60,
    approvedCost: employee.approvedCost,
    pendingHours: employee.pendingMinutes / 60,
    pendingCost: employee.pendingCost,
    unpricedHours: employee.missingRateMinutes / 60,
    averageRate: employee.averageHourlyCost,
    totalCost: { formula: `D${index + 2}+F${index + 2}`, result: employee.totalCost },
  }));
  if (!report.employees.length) addEmptySheetMessage(employees, "I", t.noRows);
  styleMoneyColumn(employees, ["approvedCost", "pendingCost", "averageRate", "totalCost"], moneyFormat);
  ["approvedHours", "pendingHours", "unpricedHours"].forEach((key) => { employees.getColumn(key).numFmt = "0.0"; });
  styleDataRows(employees);

  const tasks = prepareDataSheet(workbook, lang === "ar" ? "التاسكات" : "Tasks", [
    { header: t.task, key: "task", width: 34 },
    { header: t.due, key: "due", width: 15 },
    { header: t.status, key: "status", width: 18 },
    { header: t.estimate, key: "estimate", width: 14 },
    { header: t.approvedHours, key: "approved", width: 16 },
    { header: t.pendingHours, key: "pending", width: 16 },
    { header: t.tracked, key: "tracked", width: 14 },
    { header: t.variance, key: "variance", width: 14 },
    { header: t.remaining, key: "remaining", width: 14 },
    { header: t.cost, key: "cost", width: 18 },
  ], lang);
  report.tasks.forEach((task, index) => tasks.addRow({
    task: task.title,
    due: task.dueDate ?? null,
    status: task.status.replaceAll("_", " "),
    estimate: task.estimatedMinutes / 60,
    approved: task.approvedMinutes / 60,
    pending: task.pendingMinutes / 60,
    tracked: { formula: `E${index + 2}+F${index + 2}`, result: task.trackedMinutes / 60 },
    variance: { formula: `D${index + 2}-G${index + 2}`, result: task.hoursVariance / 60 },
    remaining: task.remainingMinutes / 60,
    cost: task.totalLaborCost,
  }));
  if (!report.tasks.length) addEmptySheetMessage(tasks, "J", t.noRows);
  tasks.getColumn("due").numFmt = "yyyy-mm-dd";
  ["estimate", "approved", "pending", "tracked", "variance", "remaining"].forEach((key) => { tasks.getColumn(key).numFmt = "0.0"; });
  styleMoneyColumn(tasks, ["cost"], moneyFormat);
  styleDataRows(tasks);

  const expenses = prepareDataSheet(workbook, lang === "ar" ? "المصاريف" : "Expenses", [
    { header: t.date, key: "date", width: 15 },
    { header: t.vendor, key: "vendor", width: 22 },
    { header: t.category, key: "category", width: 20 },
    { header: t.description, key: "description", width: 42 },
    { header: "Submitted by", key: "submittedBy", width: 22 },
    { header: t.status, key: "status", width: 16 },
    { header: t.amount, key: "amount", width: 17 },
    { header: t.tax, key: "tax", width: 17 },
    { header: t.total, key: "total", width: 17 },
  ], lang);
  report.expenses.forEach((expense, index) => expenses.addRow({
    date: expense.expenseDate,
    vendor: expense.vendor ?? "-",
    category: expense.category,
    description: expense.description,
    submittedBy: expense.submittedBy.name,
    status: expense.status,
    amount: expense.amount,
    tax: expense.taxAmount,
    total: { formula: `G${index + 2}+H${index + 2}`, result: expense.total },
  }));
  if (!report.expenses.length) addEmptySheetMessage(expenses, "I", t.noRows);
  expenses.getColumn("date").numFmt = "yyyy-mm-dd";
  styleMoneyColumn(expenses, ["amount", "tax", "total"], moneyFormat);
  styleDataRows(expenses);

  const subscriptions = prepareDataSheet(workbook, lang === "ar" ? "الاشتراكات" : "Subscriptions", [
    { header: t.description, key: "name", width: 30 },
    { header: t.vendor, key: "vendor", width: 24 },
    { header: "Frequency", key: "frequency", width: 18 },
    { header: t.allocation, key: "allocation", width: 16 },
    { header: t.periodCost, key: "periodCost", width: 18 },
    { header: t.actual, key: "actualCost", width: 18 },
    { header: t.forecast, key: "forecastCost", width: 18 },
  ], lang);
  report.subscriptions.forEach((allocation) => subscriptions.addRow({
    name: allocation.subscription.name,
    vendor: allocation.subscription.vendor,
    frequency: allocation.subscription.frequency.replaceAll("_", " "),
    allocation: allocation.allocationPercent / 100,
    periodCost: allocation.periodCost,
    actualCost: allocation.actualCost,
    forecastCost: allocation.forecastCost,
  }));
  if (!report.subscriptions.length) addEmptySheetMessage(subscriptions, "G", t.noRows);
  subscriptions.getColumn("allocation").numFmt = "0.0%";
  styleMoneyColumn(subscriptions, ["periodCost", "actualCost", "forecastCost"], moneyFormat);
  styleDataRows(subscriptions);

  const invoices = prepareDataSheet(workbook, lang === "ar" ? "الفواتير" : "Invoices", [
    { header: t.invoice, key: "invoice", width: 22 },
    { header: t.issued, key: "issued", width: 15 },
    { header: t.due, key: "due", width: 15 },
    { header: t.status, key: "status", width: 18 },
    { header: t.total, key: "total", width: 18 },
    { header: t.collected, key: "collected", width: 18 },
    { header: t.outstanding, key: "outstanding", width: 18 },
    { header: "Overdue", key: "overdue", width: 14 },
  ], lang);
  report.invoicing.invoiceRows.forEach((invoice, index) => invoices.addRow({
    invoice: invoice.number,
    issued: invoice.issueDate,
    due: invoice.dueDate,
    status: invoice.status.replaceAll("_", " "),
    total: invoice.total,
    collected: invoice.collected,
    outstanding: { formula: `MAX(E${index + 2}-F${index + 2},0)`, result: invoice.outstanding },
    overdue: invoice.overdue ? "Yes" : "No",
  }));
  if (!report.invoicing.invoiceRows.length) addEmptySheetMessage(invoices, "H", t.noRows);
  invoices.getColumn("issued").numFmt = "yyyy-mm-dd";
  invoices.getColumn("due").numFmt = "yyyy-mm-dd";
  styleMoneyColumn(invoices, ["total", "collected", "outstanding"], moneyFormat);
  styleDataRows(invoices);

  workbook.eachSheet((sheet) => {
    sheet.properties.defaultRowHeight = 19;
    sheet.headerFooter.oddFooter = `&L${t.generated}&R${t.page} &P / &N`;
  });

  const buffer = await workbook.xlsx.writeBuffer();
  return new Uint8Array(buffer);
}

export function profitabilityExportFilename(report: ProjectProfitabilityReport, lang: ReportLocale) {
  const code = report.summary.project.code.replace(/[^A-Za-z0-9_-]/g, "-").replace(/-+/g, "-");
  const from = report.range.from ? formatIsoDate(report.range.from) : "start";
  const to = report.range.to ? formatIsoDate(report.range.to) : "today";
  return `profitability-${code || "project"}-${from}-${to}-${lang}`;
}
