import "server-only";

import path from "node:path";

import PDFDocument from "pdfkit";

type DocumentLocale = "en" | "ar";

type BillingOrganization = {
  name: string;
  billingLegalName: string | null;
  billingEmail: string | null;
  billingPhone: string | null;
  billingAddress: string | null;
  taxNumber: string | null;
  website: string | null;
  bankName: string | null;
  bankAccountName: string | null;
  bankAccountNumber: string | null;
  bankIban: string | null;
  bankSwift: string | null;
  paymentTerms: string | null;
};

type InvoicePaymentDocument = {
  id: string;
  paymentDate: Date;
  amount: unknown;
  method: string;
  reference: string | null;
  notes: string | null;
  recordedBy?: { name: string };
};

type InvoiceDocument = {
  id: string;
  number: string;
  description: string;
  issueDate: Date;
  dueDate: Date;
  subtotal: unknown;
  taxAmount: unknown;
  totalAmount: unknown;
  currency: string;
  status: string;
  notes: string | null;
  organization: BillingOrganization;
  client: {
    name: string;
    legalName: string | null;
    email: string | null;
    phone: string | null;
    taxNumber: string | null;
    address: string | null;
  };
  project: { name: string; code: string };
  payments: InvoicePaymentDocument[];
};

type StatementInvoice = Omit<InvoiceDocument, "organization" | "client" | "project"> & {
  project: { name: string; code: string };
};

type StatementDocument = {
  organization: BillingOrganization;
  client: InvoiceDocument["client"];
  invoices: StatementInvoice[];
};

type QuotationDocument = {
  id: string;
  number: string;
  title: string;
  description: string | null;
  issueDate: Date;
  validUntil: Date;
  subtotal: unknown;
  discountType: string;
  discountValue: unknown;
  discountAmount: unknown;
  taxAmount: unknown;
  totalAmount: unknown;
  currency: string;
  status: string;
  notes: string | null;
  terms: string | null;
  organization: BillingOrganization;
  client: InvoiceDocument["client"];
  lineItems: Array<{
    id: string;
    description: string;
    quantity: unknown;
    unitPrice: unknown;
    taxRate: unknown;
    taxAmount: unknown;
    totalAmount: unknown;
  }>;
};

const brandFont = path.join(process.cwd(), "public", "fonts", "baloo-bhaijaan-2-semibold.ttf");
const arabicDocumentFont = path.join(process.cwd(), "public", "fonts", "dejavu-sans.ttf");
const logoPath = path.join(process.cwd(), "public", "bytech-logo.png");

const palette = {
  primary: "#435266",
  orange: "#ef7d00",
  blue: "#4997c2",
  ink: "#171717",
  gray: "#5b5b5b",
  line: "#dbdbdb",
  soft: "#f6f8fa",
  white: "#ffffff",
  success: "#28754d",
  danger: "#a13f24",
};

const copy = {
  en: {
    invoice: "INVOICE",
    receipt: "PAYMENT RECEIPT",
    statement: "CLIENT STATEMENT",
    from: "FROM",
    billTo: "BILL TO",
    receiptTo: "RECEIVED FROM",
    issueDate: "ISSUE DATE",
    dueDate: "DUE DATE",
    project: "PROJECT",
    status: "STATUS",
    description: "DESCRIPTION",
    quantity: "QTY",
    amount: "AMOUNT",
    subtotal: "Subtotal",
    tax: "Tax",
    total: "Total",
    collected: "Collected",
    outstanding: "Outstanding",
    paymentDetails: "PAYMENT DETAILS",
    paymentDate: "Payment date",
    paymentMethod: "Payment method",
    reference: "Reference",
    relatedInvoice: "Related invoice",
    amountReceived: "AMOUNT RECEIVED",
    balanceAfterPayment: "Current invoice balance",
    bankDetails: "BANK DETAILS",
    accountName: "Account name",
    accountNumber: "Account number",
    iban: "IBAN",
    swift: "SWIFT",
    notes: "NOTES",
    paymentTerms: "PAYMENT TERMS",
    statementDate: "Statement date",
    period: "Account activity to date",
    invoiceNumber: "INVOICE",
    date: "DATE",
    paid: "PAID",
    balance: "BALANCE",
    noActivity: "No issued invoices are available for this client.",
    taxNumber: "Tax no.",
    page: "Page",
    generatedBy: "Generated by Bytech Project Management",
    draft: "DRAFT",
  },
  ar: {
    invoice: "فاتورة",
    receipt: "إيصال دفع",
    statement: "كشف حساب عميل",
    from: "من",
    billTo: "فاتورة إلى",
    receiptTo: "استلمنا من",
    issueDate: "تاريخ الإصدار",
    dueDate: "تاريخ الاستحقاق",
    project: "المشروع",
    status: "الحالة",
    description: "الوصف",
    quantity: "الكمية",
    amount: "المبلغ",
    subtotal: "المبلغ قبل الضريبة",
    tax: "الضريبة",
    total: "الإجمالي",
    collected: "المبلغ المحصل",
    outstanding: "الرصيد المتبقي",
    paymentDetails: "تفاصيل الدفعة",
    paymentDate: "تاريخ الدفع",
    paymentMethod: "طريقة الدفع",
    reference: "المرجع",
    relatedInvoice: "الفاتورة المرتبطة",
    amountReceived: "المبلغ المستلم",
    balanceAfterPayment: "رصيد الفاتورة الحالي",
    bankDetails: "البيانات البنكية",
    accountName: "اسم الحساب",
    accountNumber: "رقم الحساب",
    iban: "IBAN",
    swift: "SWIFT",
    notes: "ملاحظات",
    paymentTerms: "شروط الدفع",
    statementDate: "تاريخ الكشف",
    period: "حركة الحساب حتى تاريخه",
    invoiceNumber: "الفاتورة",
    date: "التاريخ",
    paid: "المدفوع",
    balance: "الرصيد",
    noActivity: "لا توجد فواتير مصدرة لهذا العميل.",
    taxNumber: "الرقم الضريبي",
    page: "صفحة",
    generatedBy: "تم إنشاؤه بواسطة نظام إدارة مشاريع Bytech",
    draft: "مسودة",
  },
} as const;

const quotationCopy = {
  en: {
    title: "QUOTATION",
    from: "FROM",
    preparedFor: "PREPARED FOR",
    issueDate: "ISSUE DATE",
    validUntil: "VALID UNTIL",
    status: "STATUS",
    description: "DESCRIPTION",
    quantity: "QTY",
    unitPrice: "UNIT PRICE",
    tax: "TAX",
    total: "TOTAL",
    subtotal: "Subtotal",
    discount: "Discount",
    taxAmount: "Tax",
    grandTotal: "Grand total",
    terms: "TERMS & CONDITIONS",
    notes: "NOTES",
    draft: "DRAFT",
  },
  ar: {
    title: "عرض سعر",
    from: "من",
    preparedFor: "مقدم إلى",
    issueDate: "تاريخ الإصدار",
    validUntil: "صالح لغاية",
    status: "الحالة",
    description: "الوصف",
    quantity: "الكمية",
    unitPrice: "سعر الوحدة",
    tax: "الضريبة",
    total: "الإجمالي",
    subtotal: "المجموع الفرعي",
    discount: "الخصم",
    taxAmount: "الضريبة",
    grandTotal: "الإجمالي",
    terms: "الشروط والأحكام",
    notes: "ملاحظات",
    draft: "مسودة",
  },
} as const;

function createDocument(lang: DocumentLocale, title: string) {
  const doc = new PDFDocument({
    size: "A4",
    margins: { top: 44, right: 46, bottom: 48, left: 46 },
    bufferPages: true,
    info: { Title: title, Author: "Bytech", Creator: "Bytech Project Management" },
  });
  doc.registerFont("Brand", lang === "ar" ? arabicDocumentFont : brandFont);
  doc.font("Brand");
  return doc;
}

function align(lang: DocumentLocale) {
  return lang === "ar" ? "right" : "left";
}

function localizedText(value: string, lang: DocumentLocale) {
  if (lang !== "ar" || !/[\u0600-\u06ff]/.test(value)) return value;
  return value
    .split("\n")
    .map((line) => line.trim().split(/\s+/).reverse().join(" "))
    .join("\n");
}

function formatDate(date: Date) {
  return new Intl.DateTimeFormat("en-GB", {
    year: "numeric",
    month: "short",
    day: "numeric",
    timeZone: "UTC",
  }).format(date);
}

function money(value: unknown, currency: string, lang: DocumentLocale) {
  if (lang === "ar") {
    return `${currency} ${new Intl.NumberFormat("en-JO", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number(value))}`;
  }
  return new Intl.NumberFormat("en-JO", {
    style: "currency",
    currency,
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(Number(value));
}

function methodLabel(method: string, lang: DocumentLocale) {
  const english: Record<string, string> = {
    BANK_TRANSFER: "Bank transfer",
    CASH: "Cash",
    CHEQUE: "Cheque",
    CARD: "Card",
    OTHER: "Other",
  };
  const arabic: Record<string, string> = {
    BANK_TRANSFER: "تحويل بنكي",
    CASH: "نقدي",
    CHEQUE: "شيك",
    CARD: "بطاقة",
    OTHER: "أخرى",
  };
  return (lang === "ar" ? arabic : english)[method] ?? method.replaceAll("_", " ");
}

function safe(value: string | null | undefined, fallback = "-") {
  return value?.trim() || fallback;
}

function header(doc: PDFKit.PDFDocument, title: string, reference: string, lang: DocumentLocale) {
  doc.rect(0, 0, doc.page.width, 8).fill(palette.orange);
  doc.image(logoPath, 46, 34, { fit: [190, 58] });
  doc.fillColor(palette.primary).fontSize(lang === "ar" ? 22 : 25).text(localizedText(title, lang), 335, lang === "ar" ? 51 : 39, {
    width: 214,
    align: "right",
  });
  doc.fillColor(palette.gray).fontSize(11).text(reference, 335, 72, { width: 214, align: "right" });
  doc.moveTo(46, 107).lineTo(549, 107).lineWidth(1).strokeColor(palette.line).stroke();
  doc.font("Brand");
  if (lang === "ar") doc.fillColor(palette.blue);
}

function label(doc: PDFKit.PDFDocument, text: string, x: number, y: number, width: number, lang: DocumentLocale) {
  doc.fillColor(palette.blue).fontSize(8).text(localizedText(text, lang), x, y, { width, align: align(lang), characterSpacing: lang === "ar" ? 0 : 0.5 });
}

function box(doc: PDFKit.PDFDocument, x: number, y: number, width: number, height: number) {
  doc.roundedRect(x, y, width, height, 8).fillAndStroke(palette.soft, palette.line);
}

function organizationLines(organization: BillingOrganization) {
  return [
    organization.billingLegalName || organization.name,
    organization.billingAddress,
    organization.billingEmail,
    organization.billingPhone,
    organization.website,
    organization.taxNumber ? `Tax: ${organization.taxNumber}` : null,
  ].filter(Boolean).flatMap((line) => String(line).split(/\r?\n/).map((part) => part.trim()).filter(Boolean));
}

function clientLines(client: InvoiceDocument["client"]) {
  return [
    client.legalName || client.name,
    client.address,
    client.email,
    client.phone,
    client.taxNumber ? `Tax no.: ${client.taxNumber}` : null,
  ].filter(Boolean).flatMap((line) => String(line).split(/\r?\n/).map((part) => part.trim()).filter(Boolean));
}

function addressCard(
  doc: PDFKit.PDFDocument,
  title: string,
  lines: string[],
  x: number,
  y: number,
  width: number,
  lang: DocumentLocale,
) {
  box(doc, x, y, width, 112);
  label(doc, title, x + 14, y + 12, width - 28, lang);
  const textAlign = align(lang);
  lines.slice(0, 7).forEach((line, index) => {
    doc.fillColor(index === 0 ? palette.ink : palette.gray)
      .fontSize(index === 0 ? 10.5 : 8.3)
      .text(localizedText(line, lang), x + 14, y + 29 + index * 11.5, { width: width - 28, align: textAlign, lineBreak: false, ellipsis: true });
  });
}

function metric(
  doc: PDFKit.PDFDocument,
  title: string,
  value: string,
  x: number,
  y: number,
  width: number,
  lang: DocumentLocale,
) {
  label(doc, title, x, y, width, lang);
  doc.fillColor(palette.ink).fontSize(10.5).text(value, x, y + 15, { width, align: align(lang) });
}

function addFooters(doc: PDFKit.PDFDocument, lang: DocumentLocale) {
  const pages = doc.bufferedPageRange();
  for (let index = pages.start; index < pages.start + pages.count; index += 1) {
    doc.switchToPage(index);
    doc.moveTo(46, 768).lineTo(549, 768).lineWidth(0.7).strokeColor(palette.line).stroke();
    doc.fillColor(palette.gray).fontSize(8).text(localizedText(copy[lang].generatedBy, lang), 46, 777, { width: 360, align: align(lang) });
    doc.text(`${copy[lang].page} ${index + 1} / ${pages.count}`, 430, 777, { width: 119, align: "right" });
  }
}

function finish(doc: PDFKit.PDFDocument, lang: DocumentLocale) {
  return new Promise<Uint8Array>((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(new Uint8Array(Buffer.concat(chunks))));
    doc.on("error", reject);
    addFooters(doc, lang);
    doc.end();
  });
}

function paymentTotal(payments: InvoicePaymentDocument[]) {
  return payments.reduce((sum, payment) => sum + Number(payment.amount), 0);
}

export async function buildInvoicePdf(invoice: InvoiceDocument, lang: DocumentLocale) {
  const t = copy[lang];
  const doc = createDocument(lang, `${t.invoice} ${invoice.number}`);
  const collected = paymentTotal(invoice.payments);
  const balance = Math.max(Number(invoice.totalAmount) - collected, 0);
  header(doc, t.invoice, invoice.number, lang);

  addressCard(doc, t.from, organizationLines(invoice.organization), 46, 126, 242, lang);
  addressCard(doc, t.billTo, clientLines(invoice.client), 307, 126, 242, lang);

  metric(doc, t.issueDate, formatDate(invoice.issueDate), 46, 250, 112, lang);
  metric(doc, t.dueDate, formatDate(invoice.dueDate), 176, 250, 112, lang);
  metric(doc, t.project, `${invoice.project.code} - ${invoice.project.name}`, 307, 250, 150, lang);
  metric(doc, t.status, invoice.status.replaceAll("_", " "), 469, 250, 80, lang);

  const tableY = 299;
  doc.roundedRect(46, tableY, 503, 34, 6).fill(palette.primary);
  doc.fillColor(palette.white).fontSize(9);
  doc.text(t.description, 60, tableY + 11, { width: 323, align: align(lang) });
  doc.text(t.quantity, 397, tableY + 11, { width: 50, align: "center" });
  doc.text(t.amount, 459, tableY + 11, { width: 76, align: "right" });

  doc.rect(46, tableY + 34, 503, 72).fillAndStroke(palette.white, palette.line);
  doc.fillColor(palette.ink).fontSize(10.5).text(invoice.description, 60, tableY + 50, { width: 323, align: align(lang), height: 48, ellipsis: true });
  doc.text("1", 397, tableY + 50, { width: 50, align: "center" });
  doc.text(money(invoice.subtotal, invoice.currency, lang), 449, tableY + 50, { width: 86, align: "right" });

  const totalsY = 425;
  const totalRows = [
    [t.subtotal, money(invoice.subtotal, invoice.currency, lang)],
    [t.tax, money(invoice.taxAmount, invoice.currency, lang)],
    [t.total, money(invoice.totalAmount, invoice.currency, lang)],
  ];
  totalRows.forEach(([name, value], index) => {
    const y = totalsY + index * 27;
    if (index === 2) doc.roundedRect(332, y - 5, 217, 27, 5).fill(palette.primary);
    doc.fillColor(index === 2 ? palette.white : palette.gray).fontSize(index === 2 ? 11.5 : 10).text(localizedText(name, lang), 346, y, { width: 92, align: align(lang) });
    doc.text(value, 440, y, { width: 95, align: "right" });
  });

  box(doc, 46, 425, 253, 76);
  label(doc, t.collected, 60, 439, 110, lang);
  label(doc, t.outstanding, 175, 439, 110, lang);
  doc.fillColor(palette.success).fontSize(14).text(money(collected, invoice.currency, lang), 60, 458, { width: 110, align: align(lang) });
  doc.fillColor(balance > 0 ? palette.danger : palette.success).text(money(balance, invoice.currency, lang), 175, 458, { width: 110, align: align(lang) });

  const detailsY = 535;
  const hasBank = Boolean(invoice.organization.bankName || invoice.organization.bankIban || invoice.organization.bankAccountNumber);
  box(doc, 46, detailsY, 242, 218);
  label(doc, hasBank ? t.bankDetails : t.paymentTerms, 60, detailsY + 14, 214, lang);
  const bankLines = hasBank
    ? [
        invoice.organization.bankName,
        invoice.organization.bankAccountName ? `${t.accountName}: ${invoice.organization.bankAccountName}` : null,
        invoice.organization.bankAccountNumber ? `${t.accountNumber}: ${invoice.organization.bankAccountNumber}` : null,
        invoice.organization.bankIban ? `${t.iban}: ${invoice.organization.bankIban}` : null,
        invoice.organization.bankSwift ? `${t.swift}: ${invoice.organization.bankSwift}` : null,
      ].filter(Boolean) as string[]
    : [invoice.organization.paymentTerms || (lang === "ar" ? "يرجى إضافة بيانات البنك وشروط الدفع من إعدادات الفوترة." : "Add bank details and payment terms in Billing settings.")];
  doc.fillColor(palette.ink).fontSize(9.5).text(localizedText(bankLines.join("\n"), lang), 60, detailsY + 36, { width: 214, align: align(lang), lineGap: 5 });

  box(doc, 307, detailsY, 242, 218);
  label(doc, invoice.notes ? t.notes : t.paymentTerms, 321, detailsY + 14, 214, lang);
  const noteText = invoice.notes || invoice.organization.paymentTerms || (lang === "ar" ? "شكراً لتعاملكم معنا." : "Thank you for your business.");
  doc.fillColor(palette.ink).fontSize(9.5).text(localizedText(noteText, lang), 321, detailsY + 36, { width: 214, height: 162, align: align(lang), lineGap: 5, ellipsis: true });

  if (invoice.status === "DRAFT") {
    doc.save().rotate(-32, { origin: [297, 421] }).fillColor(palette.orange).opacity(0.13).fontSize(70)
      .text(t.draft, 90, 375, { width: 415, align: "center" }).opacity(1).restore();
  }

  return finish(doc, lang);
}

export async function buildReceiptPdf(
  invoice: InvoiceDocument,
  payment: InvoicePaymentDocument,
  lang: DocumentLocale,
) {
  const t = copy[lang];
  const doc = createDocument(lang, `${t.receipt} ${payment.id}`);
  const collected = paymentTotal(invoice.payments);
  const balance = Math.max(Number(invoice.totalAmount) - collected, 0);
  const receiptNumber = `RCPT-${payment.id.slice(-8).toUpperCase()}`;
  header(doc, t.receipt, receiptNumber, lang);

  addressCard(doc, t.from, organizationLines(invoice.organization), 46, 126, 242, lang);
  addressCard(doc, t.receiptTo, clientLines(invoice.client), 307, 126, 242, lang);

  box(doc, 46, 250, 503, 112);
  label(doc, t.amountReceived, 60, 266, 475, lang);
  doc.fillColor(palette.primary).fontSize(31).text(money(payment.amount, invoice.currency, lang), 60, 292, { width: 475, align: align(lang) });
  doc.fillColor(palette.gray).fontSize(10).text(`${t.relatedInvoice}: ${invoice.number}`, 60, 337, { width: 475, align: align(lang) });

  const rows = [
    [t.paymentDate, formatDate(payment.paymentDate)],
    [t.paymentMethod, methodLabel(payment.method, lang)],
    [t.reference, safe(payment.reference)],
    [t.project, `${invoice.project.code} - ${invoice.project.name}`],
    [t.balanceAfterPayment, money(balance, invoice.currency, lang)],
  ];
  box(doc, 46, 389, 503, 220);
  label(doc, t.paymentDetails, 60, 405, 475, lang);
  rows.forEach(([name, value], index) => {
    const y = 438 + index * 32;
    doc.fillColor(palette.gray).fontSize(9.5).text(localizedText(name, lang), 60, y, { width: 170, align: align(lang) });
    doc.fillColor(palette.ink).fontSize(10.5).text(localizedText(value, lang), 244, y, { width: 291, align: align(lang) });
    if (index < rows.length - 1) doc.moveTo(60, y + 22).lineTo(535, y + 22).strokeColor(palette.line).stroke();
  });

  box(doc, 46, 637, 503, 116);
  label(doc, t.notes, 60, 653, 475, lang);
  doc.fillColor(palette.ink).fontSize(10).text(localizedText(payment.notes || (lang === "ar" ? "تم استلام الدفعة وتسجيلها على حساب العميل." : "Payment received and recorded on the client account."), lang), 60, 678, { width: 475, align: align(lang), lineGap: 4 });
  return finish(doc, lang);
}

function statementHeader(
  doc: PDFKit.PDFDocument,
  data: StatementDocument,
  lang: DocumentLocale,
  totals: { invoiced: number; paid: number; balance: number; currency: string },
) {
  const t = copy[lang];
  header(doc, t.statement, data.client.name, lang);
  addressCard(doc, t.from, organizationLines(data.organization), 46, 126, 242, lang);
  addressCard(doc, t.billTo, clientLines(data.client), 307, 126, 242, lang);
  metric(doc, t.statementDate, formatDate(new Date()), 46, 250, 150, lang);
  metric(doc, t.period, "", 213, 250, 180, lang);
  metric(doc, t.outstanding, money(totals.balance, totals.currency, lang), 407, 250, 142, lang);
}

function statementTableHeader(doc: PDFKit.PDFDocument, y: number, lang: DocumentLocale) {
  const t = copy[lang];
  doc.roundedRect(46, y, 503, 30, 5).fill(palette.primary);
  doc.fillColor(palette.white).fontSize(8.5);
  doc.text(localizedText(t.invoiceNumber, lang), 58, y + 10, { width: 88, align: align(lang) });
  doc.text(localizedText(t.date, lang), 151, y + 10, { width: 75, align: align(lang) });
  doc.text(localizedText(t.total, lang), 232, y + 10, { width: 96, align: "right" });
  doc.text(localizedText(t.paid, lang), 334, y + 10, { width: 96, align: "right" });
  doc.text(localizedText(t.balance, lang), 436, y + 10, { width: 99, align: "right" });
}

export async function buildStatementPdf(data: StatementDocument, lang: DocumentLocale) {
  const t = copy[lang];
  const currency = data.invoices[0]?.currency || "JOD";
  const invoiced = data.invoices.reduce((sum, invoice) => sum + Number(invoice.totalAmount), 0);
  const paid = data.invoices.reduce((sum, invoice) => sum + paymentTotal(invoice.payments), 0);
  const balance = Math.max(invoiced - paid, 0);
  const doc = createDocument(lang, `${t.statement} - ${data.client.name}`);
  statementHeader(doc, data, lang, { invoiced, paid, balance, currency });

  let y = 298;
  statementTableHeader(doc, y, lang);
  y += 30;

  if (!data.invoices.length) {
    box(doc, 46, y, 503, 70);
    doc.fillColor(palette.gray).fontSize(10.5).text(localizedText(t.noActivity, lang), 60, y + 25, { width: 475, align: "center" });
    y += 88;
  } else {
    for (const invoice of data.invoices) {
      if (y > 742) {
        doc.addPage();
        header(doc, t.statement, data.client.name, lang);
        y = 130;
        statementTableHeader(doc, y, lang);
        y += 30;
      }
      const invoicePaid = paymentTotal(invoice.payments);
      const invoiceBalance = Math.max(Number(invoice.totalAmount) - invoicePaid, 0);
      doc.rect(46, y, 503, 40).fillAndStroke(palette.white, palette.line);
      doc.fillColor(palette.ink).fontSize(9.5).text(invoice.number, 58, y + 9, { width: 88, align: align(lang) });
      doc.fillColor(palette.gray).fontSize(7.5).text(invoice.project.name, 58, y + 24, { width: 88, height: 11, ellipsis: true, align: align(lang) });
      doc.fillColor(palette.ink).fontSize(9).text(formatDate(invoice.issueDate), 151, y + 14, { width: 75, align: align(lang) });
      doc.text(money(invoice.totalAmount, invoice.currency, lang), 232, y + 14, { width: 96, align: "right" });
      doc.text(money(invoicePaid, invoice.currency, lang), 334, y + 14, { width: 96, align: "right" });
      doc.fillColor(invoiceBalance > 0 ? palette.danger : palette.success).text(money(invoiceBalance, invoice.currency, lang), 436, y + 14, { width: 99, align: "right" });
      y += 40;
    }
  }

  if (y > 670) {
    doc.addPage();
    header(doc, t.statement, data.client.name, lang);
    y = 140;
  } else {
    y += 22;
  }
  box(doc, 297, y, 252, 104);
  const totalRows = [
    [t.total, money(invoiced, currency, lang)],
    [t.collected, money(paid, currency, lang)],
    [t.outstanding, money(balance, currency, lang)],
  ];
  totalRows.forEach(([name, value], index) => {
    const rowY = y + 15 + index * 27;
    doc.fillColor(index === 2 ? palette.primary : palette.gray).fontSize(index === 2 ? 11 : 9.5).text(localizedText(name, lang), 311, rowY, { width: 98, align: align(lang) });
    doc.text(value, 413, rowY, { width: 122, align: "right" });
  });
  return finish(doc, lang);
}

function quotationTableHeader(doc: PDFKit.PDFDocument, y: number, lang: DocumentLocale) {
  const t = quotationCopy[lang];
  doc.roundedRect(46, y, 503, 32, 5).fill(palette.primary);
  doc.fillColor(palette.white).fontSize(8);
  doc.text(localizedText(t.description, lang), 58, y + 11, { width: 205, align: align(lang) });
  doc.text(localizedText(t.quantity, lang), 269, y + 11, { width: 45, align: "center" });
  doc.text(localizedText(t.unitPrice, lang), 318, y + 11, { width: 74, align: "right" });
  doc.text(localizedText(t.tax, lang), 398, y + 11, { width: 55, align: "right" });
  doc.text(localizedText(t.total, lang), 459, y + 11, { width: 76, align: "right" });
}

function quotationHeader(doc: PDFKit.PDFDocument, reference: string, lang: DocumentLocale) {
  const title = lang === "ar" ? "QUOTATION" : quotationCopy.en.title;
  header(doc, title, reference, lang);
  if (lang === "ar") {
    doc.rect(40, 25, 245, 76).fill(palette.white);
    doc.image(logoPath, 46, 34, { fit: [190, 58] });
    doc.rect(320, 25, 229, 76).fill(palette.white);
    doc.fillColor(palette.primary).fontSize(23).text(title, 335, 39, { width: 214, align: "right" });
    doc.fillColor(palette.gray).fontSize(11).text(reference, 335, 72, { width: 214, align: "right" });
    doc.moveTo(46, 107).lineTo(549, 107).lineWidth(1).strokeColor(palette.line).stroke();
  }
}

export async function buildQuotationPdf(quotation: QuotationDocument, lang: DocumentLocale) {
  const t = quotationCopy[lang];
  const doc = createDocument(lang, `${t.title} ${quotation.number}`);
  quotationHeader(doc, quotation.number, lang);
  addressCard(doc, t.from, organizationLines(quotation.organization), 46, 126, 242, lang);
  addressCard(doc, t.preparedFor, clientLines(quotation.client), 307, 126, 242, lang);
  metric(doc, t.issueDate, formatDate(quotation.issueDate), 46, 250, 120, lang);
  metric(doc, t.validUntil, formatDate(quotation.validUntil), 181, 250, 120, lang);
  metric(doc, t.status, quotation.status.replaceAll("_", " "), 420, 250, 129, lang);
  doc.fillColor(palette.ink).fontSize(12).text(localizedText(quotation.title, lang), 46, 279, { width: 503, align: align(lang), height: 22, ellipsis: true });

  let y = 309;
  quotationTableHeader(doc, y, lang);
  y += 32;
  for (const item of quotation.lineItems) {
    if (y > 695) {
      doc.addPage();
      quotationHeader(doc, quotation.number, lang);
      y = 128;
      quotationTableHeader(doc, y, lang);
      y += 32;
    }
    doc.rect(46, y, 503, 43).fillAndStroke(palette.white, palette.line);
    doc.fillColor(palette.ink).fontSize(9.2).text(localizedText(item.description, lang), 58, y + 8, { width: 205, height: 29, align: align(lang), ellipsis: true });
    doc.text(String(Number(item.quantity)), 269, y + 14, { width: 45, align: "center" });
    doc.text(money(item.unitPrice, quotation.currency, lang), 318, y + 14, { width: 74, align: "right" });
    doc.text(`${Number(item.taxRate)}%`, 398, y + 14, { width: 55, align: "right" });
    doc.text(money(item.totalAmount, quotation.currency, lang), 459, y + 14, { width: 76, align: "right" });
    y += 43;
  }

  if (y > 610) {
    doc.addPage();
    quotationHeader(doc, quotation.number, lang);
    y = 135;
  } else {
    y += 20;
  }

  box(doc, 307, y, 242, 130);
  const totalRows = [
    [t.subtotal, money(quotation.subtotal, quotation.currency, lang)],
    [t.discount, `- ${money(quotation.discountAmount, quotation.currency, lang)}`],
    [t.taxAmount, money(quotation.taxAmount, quotation.currency, lang)],
    [t.grandTotal, money(quotation.totalAmount, quotation.currency, lang)],
  ];
  totalRows.forEach(([name, value], index) => {
    const rowY = y + 15 + index * 27;
    if (index === totalRows.length - 1) doc.roundedRect(319, rowY - 5, 218, 26, 5).fill(palette.primary);
    doc.fillColor(index === totalRows.length - 1 ? palette.white : palette.gray).fontSize(index === totalRows.length - 1 ? 10.5 : 9.5).text(localizedText(name, lang), 321, rowY, { width: 92, align: align(lang) });
    doc.text(value, 415, rowY, { width: 120, align: "right" });
  });

  box(doc, 46, y, 242, 130);
  label(doc, quotation.description ? t.description : t.notes, 60, y + 15, 214, lang);
  const summary = quotation.description || quotation.notes || "-";
  doc.fillColor(palette.ink).fontSize(9.5).text(localizedText(summary, lang), 60, y + 39, { width: 214, height: 75, align: align(lang), lineGap: 4, ellipsis: true });
  y += 150;

  if (y > 625) {
    doc.addPage();
    quotationHeader(doc, quotation.number, lang);
    y = 135;
  }
  box(doc, 46, y, 242, 128);
  label(doc, t.terms, 60, y + 15, 214, lang);
  doc.fillColor(palette.ink).fontSize(9.2).text(localizedText(quotation.terms || quotation.organization.paymentTerms || "-", lang), 60, y + 38, { width: 214, height: 72, align: align(lang), lineGap: 4, ellipsis: true });
  box(doc, 307, y, 242, 128);
  label(doc, t.notes, 321, y + 15, 214, lang);
  doc.fillColor(palette.ink).fontSize(9.2).text(localizedText(quotation.notes || "-", lang), 321, y + 38, { width: 214, height: 72, align: align(lang), lineGap: 4, ellipsis: true });

  if (quotation.status === "DRAFT") {
    const pages = doc.bufferedPageRange();
    for (let index = pages.start; index < pages.start + pages.count; index += 1) {
      doc.switchToPage(index);
      doc.save().rotate(-32, { origin: [297, 421] }).fillColor(palette.orange).opacity(0.12).fontSize(64)
        .text(localizedText(t.draft, lang), 90, 375, { width: 415, align: "center" }).opacity(1).restore();
    }
  }
  return finish(doc, lang);
}
